---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yiguangzheng.
--- DateTime: 2021/6/3 下午10:16
---
---
local function assert(v)
    if not v then
        fail()
    end
end

local function a()
    return 2,3,4
end

local b = { 1, a() }
assert(b[1] == 1)
assert(b[2] == 2)
assert(b[3] == 3)
assert(b[4] == 4)
