---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Yiklek.
--- DateTime: 2021/6/2 下午3:41
---

local t = { "a", "b", "c" }
t[2] = "B"
t["foo"] = "Bar"
local s = t[3] .. t[2] .. t[1] .. t["foo"] .. #t