---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Yiklek.
--- DateTime: 2021/6/29 下午5:37
---
local function assert(v)
    if not v then
        fail()
    end
end
function newCounter()
    local count = 0
    return function()
        count = count + 1
        return count
    end
end

c1 = newCounter()
assert(c1() == 1)
assert(c1() == 2)

c2 = newCounter()
assert(c2() == 1)
assert(c1() == 3)
assert(c2() == 2)
