---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yiguangzheng.
--- DateTime: 2021/6/1 下午9:39
---
local sum = 0
for i = 1, 100 do
    if i % 2 == 0 then
        sum = sum + i
    end
end